### ISSUE TITLE
Nodes in ComfyUI Manager

### ISSUE THREAD

**Issue by alessandroperilli** [black-forest-labs/bfl-comfy-nodes#3]
I'd like to add support for Flux Pro models to my [AP Workflow for ComfyUI](https://perilli.com/ai/comfyui/), but its installation is already very complicated as is. Is there any chance the team can register this node suite into ComfyUI Manager?

Thank you for considering this request.

**Comment by Tobe2d** [comment]
+1

**Comment by Klace** [comment]
Done!
