### ISSUE TITLE
Support for new Flux Tools models? Passing input images to the API?

### ISSUE THREAD

**Issue by martintomov** [black-forest-labs/bfl-comfy-nodes#7]
Hi! Do you plan to add support for `flux-pro-1.0-fill`, `flux-pro-1.0-canny`, and `flux-pro-1.0-depth` in your Comfy nodes?

**Comment by Thingerbuddy** [comment]
+1 to the question on whether you plan to support these

**Comment by QueryType** [comment]
Very much required.

**Comment by Klace** [comment]
Added! Sorry for the long wait commit 94f5f99
